### ISSUE TITLE
[BUG] could not login with metamask/GitHub account

### ISSUE THREAD

**Issue by whyouare111** [w3itch-crafter/w3itch-backend#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/171697391-54b4304b-ffa5-42d4-94ac-8792662e26c3.png)

Seems fixed.
