### ISSUE TITLE
[BUG] Game file could not be downloaded if I upload a zip file with a new name

### ISSUE THREAD

**Issue by whyouare111** [w3itch-crafter/w3itch-backend#54]
**Describe the bug**

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Edit' on a game project
3. update a new game file,click on 'Update'
4. open game page,click on 'Download'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Syntacticlosure** [comment]
fix by #65
