### ISSUE TITLE
[FEAT] Game file download API

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-backend#7]
**Is your feature request related to a problem? Please describe.**
Sometimes uploaded games have features that are not compatible with the web player, or there are resources that cannot be uploaded for copyright reasons, but I still want to use w3ich.io as a resource distribution point for players to download games for testing and playing.

**Describe the solution you'd like**
Game file can be download on game page,like itch.io

**Comment by remi-guan** [comment]
The feature has been implemented in the commit d56aea66f532fa60a4b95
Waiting for the front-end to integrate.
